queue_rules:
  - name: renovate
    conditions:
      - author=renovate[bot]
      - author=pre-commit-ci[bot]
      - status-success=build

pull_request_rules:
  - name: merge pull requests from renovate bot if CI passes
    conditions:
      - author=renovate[bot]
      - author=pre-commit-ci[bot]
      - status-success=build
    actions:
      queue:
        name: deps
