# ruff: noqa: E501

from fabric.utils import GLib, get_relative_path, re

# constants

HOME_DIR = GLib.get_home_dir()

NOTIFICATION_WIDTH = 400
NOTIFICATION_IMAGE_SIZE = 78
HIGH_POLL_INTERVAL = 3600  # 1 hour in seconds
MONITOR_HOTPLUG_DELAY_MS = 500  # Delay for monitor hotplug recreation

# Network service constants
NETWORK_RECENCY_THRESHOLD_SECONDS = 300  # 5 minutes for WiFi network freshness

APPLICATION_NAME = "tsumiki"
SYSTEM_CACHE_DIR = GLib.get_user_data_dir()
APP_DATA_DIRECTORY = f"{SYSTEM_CACHE_DIR}/{APPLICATION_NAME}"


NOTIFICATION_CACHE_FILE = f"{APP_DATA_DIRECTORY}/notifications.json"
WEATHER_CACHE_FILE = f"{APP_DATA_DIRECTORY}/weather.json"
FX_RATES_CACHE_FILE = f"{APP_DATA_DIRECTORY}/fx_rates.json"
QUOTES_CACHE_FILE = f"{APP_DATA_DIRECTORY}/quotes.json"
ICON_CACHE_FILE = f"{APP_DATA_DIRECTORY}/icons.json"
PINNED_APPS_FILE = f"{APP_DATA_DIRECTORY}/pinned_apps.json"
KANBAN_FILE = f"{APP_DATA_DIRECTORY}/kanban.json"
CSS_PATH = f"{APP_DATA_DIRECTORY}/main.css"


ASSETS_DIR = get_relative_path("../assets/")

WALLPAPER_DIR = f"{HOME_DIR}/Pictures/Wallpapers"
WALLPAPER_THUMBS_DIR = f"{WALLPAPER_DIR}/.thumbs"
WALLPAPER_BLURRED_DIR = f"{WALLPAPER_DIR}/.blurred"

USER_STATE_DIR = GLib.get_user_state_dir()
LOG_DIR = f"{USER_STATE_DIR}/{APPLICATION_NAME}/logs"
LOG_FILE = f"{LOG_DIR}/{APPLICATION_NAME}.log"
LOG_FORMAT = "{time:YYYY-MM-DD HH:mm:ss} [<level>{level}</level>] {message}"


# Default configuration values
DEFAULT_CONFIG = {
    "$schema": f"./{APPLICATION_NAME}.schema.json",
    "widgets": {
        "launcher_button": {
            "icon": "view-app-grid-symbolic",
            "icon_size": 16,
            "tooltip": True,
        },
        "clipboard": {
            "icon": "",
            "label": False,
            "tooltip": True,
            "item_tooltip": False,
            "show_images": True,
        },
        "breathe": {
            "icon": "",
            "label": False,
            "tooltip": True,
        },
        "emoji_picker": {
            "icon": "",
            "label": False,
            "tooltip": True,
            "per_row": 9,
            "per_column": 4,
        },
        "kanban": {
            "icon": "󱞁",
            "label": True,
            "tooltip": True,
        },
        "battery": {
            "full_battery_level": 100,
            "hide_percent_when_full": True,
            "hide_when_missing": True,
            "icons": ["", "", "", "", ""],
            "tooltip": True,
            "label_format": "{icon} {percent}",
            "notifications": {
                "low_battery": {
                    "enabled": False,
                    "threshold": 10,
                    "message": "",
                },
                "full_battery": {
                    "enabled": False,
                    "message": "",
                },
                "charging": {
                    "enabled": False,
                    "message": "",
                },
                "unplugged": {
                    "enabled": False,
                    "message": "",
                },
            },
        },
        "quick_settings": {
            "hover_reveal": False,
            "toggles": [
                "wifi",
                "bluetooth",
                "power_profiles",
                "hyprsunset",
                "hypridle",
                "notification",
            ],
            "user": {"avatar": "~/.face", "name": "system", "distro_icon": True},
            "controls": {
                "sliders": ["brightness", "volume"],
            },
            "media": {
                "enabled": True,
                "ignore": [],
                "truncation_size": 30,
                "show_album": True,
                "show_artist": True,
                "show_player_icon": True,
                "show_time": True,
                "show_time_tooltip": True,
            },
            "shortcuts": {
                "enabled": True,
                "items": [],
            },
        },
        "bluetooth": {
            "label": True,
            "tooltip": True,
        },
        "brightness": {
            "tooltip": True,
            "step_size": 5,
        },
        "wallpaper": {"icon": "󰸉", "label": False, "tooltip": True},
        "cava": {"bars": 10, "color": "#89b4fa"},
        "overview_button": {"icon": "󰡃", "tooltip": True, "label": False},
        "click_counter": {"count": 0},
        "dns_switcher": {"count": 0},
        "cloudflare_warp": {"count": 0},
        "cpu": {
            "show_icon": True,
            "icon": "",
            "tooltip": True,
            "round": True,
            "temperature_unit": "celsius",
            "show_unit": True,
            "sensor": "",
            "mode": "circular",
            "graph_length": 4,
        },
        "gpu": {
            "show_icon": True,
            "icon": "",
            "tooltip": True,
            "mode": "circular",
            "graph_length": 4,
        },
        "settings": {"icon": "󰒓", "tooltip": True, "label": False},
        "date_time": {
            "date_format": "%b %d",
            "calendar": True,
            "clock_format": "12h",
            "hover_reveal": False,
            "reveal_duration": 500,
            "extended_date": False,
            "notification": {
                "enabled": True,
                "count": True,
                "hide_count_on_zero": False,
                "notification_grouping": True,  # Group history by app in the date menu
            },
        },
        "divider": {"size": 2},
        "cheatsheet": {},
        "github_tray": {
            "icon": "",
            "label": False,
            "label_text": "GitHub",
            "tooltip": True,
            "username": "",
            "hostname": "",
            "avatar_size": 44,
            "default_tab": "inbox",
            "max_repos": 10,
            "sort_by": "updated",
            "sort_order": "desc",
            "own_repos_only": False,
            "cache_ttl": 3600,
            "notification_interval": 60,
            "workflow_runs_max": 10,
            "show_notifications": True,
            "notify_reasons": {
                "review_requests": True,
                "mentions": True,
                "assignments": True,
                "pr_comments": True,
                "issue_comments": True,
            },
            "alerts": {
                "enabled": True,
                "new_stars": True,
                "new_forks": True,
                "new_issues": True,
                "new_followers": True,
                "new_notifications": True,
                "workflow_started": True,
                "workflow_success": True,
                "workflow_failure": True,
                "workflow_cancelled": True,
            },
            "local_editor": "code",
            "local_projects": {},
        },
        "pomodoro": {
            "icon": "🍅",
            "label": True,
            "label_text": "Pomo",
            "tooltip": True,
        },
        "ip_monitor": {},
        "hypridle": {
            "enabled_icon": "",
            "disabled_icon": "",
            "label": True,
            "tooltip": True,
        },
        "hyprpicker": {
            "icon": "",
            "tooltip": True,
            "label": False,
            "quiet": False,
            "show_icon": True,
        },
        "hyprsunset": {
            "temperature": "2800k",
            "enabled_icon": "󱩌",
            "disabled_icon": "󰛨",
            "label": True,
            "tooltip": True,
        },
        "keyboard": {
            "icon": "󰌌",
            "label": True,
            "tooltip": True,
            "show_icon": True,
        },
        "window_count": {
            "label_format": " [{count}]",
            "hide_when_zero": True,
            "tooltip": True,
        },
        "language": {
            "icon": "",
            "tooltip": True,
            "truncation_size": 2,
            "show_icon": True,
        },
        "widget_groups": [
            {
                "widgets": ["updates", "battery"],
                "spacing": 4,
                "style_classes": ["bordered"],
                "hover_reveal": False,
                "reveal_duration": 500,
            },
            {
                "widgets": ["quick_settings", "cpu"],
                "spacing": 0,
                "style_classes": ["compact"],
                "hover_reveal": False,
                "reveal_duration": 500,
            },
        ],
        "memory": {
            "show_icon": True,
            "icon": "",
            "tooltip": True,
            "mode": "circular",
            "graph_length": 4,
            "unit": "gb",
        },
        "network_usage": {
            "tooltip": True,
            "label_format": " {upload}  {download}",
            "upload_threshold": 100,
            "download_threshold": 1024,
            "kb_digits": 0,
            "mb_digits": 2,
            "interval": 2000,
        },
        "microphone": {
            "label": False,
            "tooltip": True,
            "show_icon": True,
        },
        "mpris": {
            "truncation_size": 20,
            "tooltip": True,
            "label_format": "{title} - {artist}",
            "hide_when_no_player": True,
            "ignore": [],
        },
        "ocr": {
            "icon": "󰐳",
            "tooltip": True,
            "label": False,
            "show_icon": True,
            "quiet": False,
        },
        "power": {
            "icon": "󰐥",
            "tooltip": True,
            "items_per_row": 3,
            "icon_size": 100,
            "show_icon": True,
            "label": False,
            "confirm": True,
            "buttons": {
                "shutdown": "systemctl poweroff",
                "reboot": "systemctl reboot",
                "hibernate": "systemctl hibernate",
                "suspend": "systemctl suspend",
                "lock": "loginctl lock-session",
                "logout": "loginctl terminate-user $USER",
            },
        },
        "recorder": {
            "path": "Videos/Screencasting",
            "tooltip": True,
            "audio": True,
            "delayed": False,
            "delayed_timeout": 5000,
        },
        "screenshot": {
            "path": "Pictures/Screenshots",
            "icon": "󰄀",
            "tooltip": True,
            "annotation": True,
            "delayed": False,
            "delayed_timeout": 5000,
            "label": False,
            "capture_sound": False,
        },
        "stopwatch": {"stopped_icon": "󱫞", "running_icon": "󱫠"},
        "storage": {
            "path": "/",
            "show_icon": True,
            "icon": "󰋊",
            "mode": "circular",
            "tooltip": True,
            "graph_length": 4,
            "unit": "gb",  # Default unit for storage
        },
        "submap": {
            "icon": "󰌌",
            "label": True,
            "tooltip": True,
            "show_icon": True,
            "hide_on_default": False,
        },
        "system_tray": {
            "icon_size": 16,
            "ignored": [],
            "hidden": [],
            "hide_when_empty": False,
            "tooltip": True,
        },
        "taskbar": {
            "icon_size": 22,
            "ignored": [],
            "tooltip": True,
            "show_current_workspace_only": False,
        },
        "theme_switcher": {
            "icon": "",
            "notify": False,  # Whether to show a notification when the theme is changed
        },
        "updates": {
            "show_icon": True,
            "available_icon": "󰏗",
            "no_updates_icon": "󰏖",
            "os": "arch",
            "hover_reveal": False,  # Whether to reveal the updates on hover
            "reveal_duration": 500,
            "interval": HIGH_POLL_INTERVAL,
            "tooltip": True,
            "terminal": "kitty",
            "pad_zero": True,  # Whether to pad the number of updates with zero
            "label": True,
            "auto_hide": False,  # Whether to auto-hide there are no updates
            "flatpak": False,
            "snap": False,
            "brew": False,
        },
        "usb_manager": {
            "icon": "",
            "label": False,
            "tooltip": True,
            "auto_refresh": True,
            "refresh_interval": 5,
        },
        "volume": {
            "tooltip": True,
            "step_size": 5,
        },
        "weather": {
            "location": "",
            "label_format": "{condition} {temperature}",
            "tooltip": True,
            "expanded": True,
            "temperature_unit": "celsius",
            "wind_speed_unit": "kmh",
            "interval": HIGH_POLL_INTERVAL,
            "hover_reveal": False,
        },
        "window_title": {
            "icon": True,
            "truncation": True,
            "truncation_size": 20,
            "tooltip": True,
            "mappings": True,
            "title_map": [],
            "fallback": "class",
        },
        "workspaces": {
            "count": 10,
            "hide_unoccupied": True,
            "ignored": [-99],
            "reverse_scroll": False,
            "style": "numbered",
            "empty_scroll": False,
            "label_format": "{id}",
            "icon_map": {},
            "show_special": False,
        },
        "world_clock": {
            "icon": "󱉊'",
            "use_24hr": True,
            "show_icon": True,
            "timezones": ["America/New_York", "Asia/Tokyo"],
        },
        "custom_button_group": {
            "buttons": [],
            "spacing": 4,
        },
    },
    "layout": {
        "left_section": ["workspaces", "window_title"],
        "middle_section": ["date_time"],
        "right_section": ["system_tray"],
    },
    "modules": {
        "bar": {
            "layer": "top",
            "auto_hide": False,
            "auto_hide_timeout": 3000,
            "location": "top",
        },
        "overview": {
            "enabled": False,
            "layer": "top",
            "anchor": "center",
            "transition_type": "crossfade",
            "transition_duration": 350,
        },
        "osd": {
            "enabled": False,
            "timeout": 1500,
            "anchor": "bottom-center",
            "orientation": "horizontal",
            "percentage": True,
            "icon_size": 28,
            "play_sound": False,
            "transition_type": "slide-up",
            "transition_duration": 500,
            "osds": ["brightness", "volume"],
            "poll_interval": 200,
        },
        "launcher": {
            "enabled": False,
            "tooltip": True,
            "icon_size": 16,
            "plugins_enabled": True,
            "plugins": [],
        },
        "notification": {
            "enabled": True,
            "anchor": "top-right",
            "auto_dismiss": True,
            "dnd_on_screencast": False,  # Enable Do Not Disturb mode when screencasting
            "ignored": [],
            "respect_expire": True,  # Whether to respect the expire timeout sent by the notification
            "timeout": {"low": 3000, "normal": 8000, "critical": 15000},
            "transition_type": "slide-left",
            "transition_duration": 350,
            "per_app_limits": {},
            "play_sound": False,
            "max_actions": 3,
            "copy_code_action": True,  # Offer COPY for one-time (2FA) codes in body
            "show_timestamp": True,  # Relative timestamp in notification header
            "dismiss_on_hover": False,
            "sound_file": "notification4",
            "persist": {
                "enabled": True,
                "max_count": 200,
                "low": True,
                "normal": True,
                "critical": True,
            },
        },
        "screen_corners": {
            "enabled": False,
            "size": 20,
        },
        "dock": {
            "enabled": False,
            "ignored": [],
            "icon_size": 40,
            "behavior": "intellihide",  # can be "always_show" or "intellihide"
            "tooltip": False,
            "layer": "top",
            "show_when_no_windows": False,
            "group_apps": True,
            "truncation_size": 20,
            "orientation": "horizontal",
            "always_show_focused": True,
            "show_launcher": True,
            "launcher_position": "first",
            "hide_special_workspace_apps": False,
        },
        "desktop_clock": {
            "enabled": False,
            "layer": "bottom",
            "anchor": "center",
            "date_format": "%A, %d %B %Y",
            "time_format": "%H:%M",
            "extended_date": False,
        },
        "desktop_quotes": {
            "enabled": False,
            "anchor": "bottom-right",
            "layer": "bottom",
            "interval": 600,
        },
        "activate_linux": {
            "enabled": False,
            "anchor": "bottom-right",
            "layer": "bottom",
        },
    },
    "general": {
        "check_updates": False,
        "debug": True,
        "monitor_styles": True,
        "auto_restart": True,
        "restart_delay": 1500,
        "multi_monitor": False,
        "tooltips": True,
        "language": "en",
    },
    "styling": {
        "bar": {
            "border": {"enabled": True, "radius": "16px", "width": "4px"},
            "buttons": {
                "hover_opacity": 90,
                "margin_x": "0",
                "margin_y": "1.25em",
                "opacity": 100,
                "padding_x": "0",
                "padding_y": "1.25em",
                "scaling": 100,
                "shadow": {
                    "blur": 0,
                    "enabled": False,
                    "offset": 0,
                    "opacity": 100,
                    "spread": 0,
                },
            },
            "margin_x": "0",
            "margin_y": "1.25em",
            "menus": {
                "border": {"enabled": False, "radius": "16px", "width": "1px"},
                "opacity": 100,
                "popover": {
                    "border": {"enabled": False, "radius": "1.5em", "width": "1px"},
                    "font-weight": 700,
                    "margin_x": "0",
                    "margin_y": "1.25em",
                    "opacity": 100,
                    "padding_x": "0.5em",
                    "padding_y": "0.5em",
                    "scaling": 100,
                    "shadow": {
                        "blur": 0,
                        "enabled": False,
                        "offset": 0,
                        "opacity": 100,
                        "spread": 0,
                    },
                },
                "scaling": 100,
                "tooltip": {
                    "border": {"enabled": False, "radius": "1em", "width": "1px"},
                    "font-weight": 700,
                    "opacity": 100,
                    "padding_x": "0.25em",
                    "padding_y": "0.125em",
                    "scaling": 100,
                    "shadow": {
                        "blur": 0,
                        "enabled": False,
                        "offset": 0,
                        "opacity": 100,
                        "spread": 0,
                    },
                },
            },
            "opacity": 10,
            "padding_x": "0.8em",
            "padding_y": "0.6em",
            "scaling": 100,
            "shadow": {
                "blur": 0,
                "enabled": False,
                "offset": 0,
                "opacity": 100,
                "spread": 0,
            },
            "style": {"panel": "default", "widget": "default"},
            "widgets": {
                "battery": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "bluetooth": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "brightness": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.25em",
                },
                "cava": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "spacing": "0.125em",
                },
                "cheatsheet": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "click_counter": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "clipboard": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "cloudflare_warp": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "cpu": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "custom_button": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "custom_widget": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "date_time": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "divider": {"margin_x": "0", "margin_y": "1.25em", "size": " 2px"},
                "dns_switcher": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "emoji_picker": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "gap": "2px",
                "github_tray": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "hypridle": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "hyprpicker": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "hyprsunset": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "ip_monitor": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "kanban": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "keyboard": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "language": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "launcher_button": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "memory": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "microphone": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "mpris": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "network_usage": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "ocr": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "overview": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "overview_button": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "pomodoro": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "power": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "quick_settings": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "17px",
                    "sliders": {"height": "7px", "knob": True, "knob_height": "8px"},
                    "spacing": "0.125em",
                },
                "radio_player": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "recorder": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "screenshot": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "spacing": {"size": " 20px"},
                "stopwatch": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "storage": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "submap": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "system_tray": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "spacing": "0.3em",
                },
                "taskbar": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "spacing": "0.125em",
                },
                "theme": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "theme_switcher": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "updates": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "usb_manager": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "volume": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
                "weather": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "17px",
                    "spacing": "0.125em",
                },
                "window_count": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "spacing": "0.125em",
                },
                "window_title": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "14px",
                    "spacing": "0.125em",
                },
                "workspaces": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "pill": {
                        "active_width": "1em",
                        "border": {"enabled": False, "radius": "16px", "width": "2px"},
                        "height": "1px",
                        "width": "0.5em",
                    },
                    "spacing": "0.125em",
                },
                "world_clock": {
                    "border": {"enabled": False, "radius": "16px", "width": "1px"},
                    "icon_size": "12px",
                    "spacing": "0.125em",
                },
            },
        },
        "border-radius": "10px",
        "border-width": "1px",
        "font": {
            "name": "JetBrainsMono Nerd Font Propo",
            "size": "1rem",
            "style": "normal",
            "weight": 600,
        },
        "matugen": {
            "contrast": 0,
            "enabled": False,
            "scheme": "scheme-tonal-spot",
            "wallpaper": "~/2.jpg",
        },
        "mode": "dark",
        "modules": {
            "activate_linux": {
                "border": {"enabled": False, "radius": "16px", "width": "1px"},
                "spacing": "0.125em",
            },
            "desktop_clock": {
                "border": {"enabled": False, "radius": "16px", "width": "1px"},
                "spacing": "0.125em",
            },
            "desktop_quotes": {
                "border": {"enabled": False, "radius": "16px", "width": "1px"},
                "spacing": "0.125em",
            },
            "dock": {
                "border": {"enabled": False, "radius": "1.5rem", "width": "1px"},
                "margin_x": "8px",
                "margin_y": "8px",
                "opacity": 10,
                "padding_x": "8px",
                "padding_y": "4px",
                "scaling": 100,
                "shadow": {
                    "blur": 0,
                    "enabled": False,
                    "offset": 0,
                    "opacity": 100,
                    "spread": 0,
                },
            },
            "launcher": {
                "border": {"enabled": False, "radius": "1.5rem", "width": "1px"},
                "margin_x": "8px",
                "margin_y": "8px",
                "opacity": 50,
                "padding_x": "8px",
                "padding_y": "8px",
                "scaling": 100,
                "shadow": {
                    "blur": 0,
                    "enabled": False,
                    "offset": 0,
                    "opacity": 100,
                    "spread": 0,
                },
            },
            "notification": {
                "border": {"enabled": False, "radius": "16px", "width": "1px"},
                "margin_x": "0",
                "margin_y": "1.25em",
                "opacity": 100,
                "padding_x": "0.9em",
                "padding_y": "0.9em",
                "scaling": 100,
                "shadow": {
                    "blur": 0,
                    "enabled": False,
                    "offset": 0,
                    "opacity": 100,
                    "spread": 0,
                },
            },
            "osd": {
                "border": {"enabled": False, "radius": "25px", "width": "1px"},
                "margin_x": "0",
                "margin_y": "1.25em",
                "opacity": 100,
                "padding_x": "0.8em",
                "padding_y": "0.6em",
                "scaling": 100,
                "shadow": {
                    "blur": 0,
                    "enabled": False,
                    "offset": 0,
                    "opacity": 100,
                    "spread": 0,
                },
                "sliders": {"height": "7px", "knob": False, "knob_height": "8px"},
                "widget_style": "default",
            },
        },
        "padding": "7pt",
        "spacing": "12pt",
        "theme_name": "catpuccin-mocha",
    },
}

# Lazy-loaded keyboard layout map - only loaded when keyboard widget is used
_KBLAYOUT_MAP = None


def get_kblayout_map() -> dict:
    """Get keyboard layout map, loading it lazily on first access."""
    global _KBLAYOUT_MAP
    if _KBLAYOUT_MAP is None:
        _KBLAYOUT_MAP = _create_kblayout_map()
    return _KBLAYOUT_MAP


def _create_kblayout_map() -> dict:
    """Create the keyboard layout map. Sourced from hyprpanel."""
    return {
        "Abkhazian (Russia)": "RU (Ab)",
        "Akan": "GH (Akan)",
        "Albanian": "AL",
        "Albanian (Plisi)": "AL (Plisi)",
        "Albanian (Veqilharxhi)": "AL (Veqilharxhi)",
        "Amharic": "ET",
        "Arabic": "ARA",
        "Arabic (Algeria)": "DZ (Ar)",
        "Arabic (AZERTY, Eastern Arabic numerals)": "ARA (Azerty Digits)",
        "Arabic (AZERTY)": "ARA (Azerty)",
        "Arabic (Buckwalter)": "ARA (Buckwalter)",
        "Arabic (Eastern Arabic numerals)": "ARA (Digits)",
        "Arabic (Macintosh)": "ARA (Mac)",
        "Arabic (Morocco)": "MA",
        "Arabic (OLPC)": "ARA (Olpc)",
        "Arabic (Pakistan)": "PK (Ara)",
        "Arabic (QWERTY, Eastern Arabic numerals)": "ARA (Qwerty Digits)",
        "Arabic (QWERTY)": "ARA (Qwerty)",
        "Arabic (Syria)": "SY",
        "Armenian": "AM",
        "Armenian (alt. eastern)": "AM (Eastern-Alt)",
        "Armenian (alt. phonetic)": "AM (Phonetic-Alt)",
        "Armenian (eastern)": "AM (Eastern)",
        "Armenian (phonetic)": "AM (Phonetic)",
        "Armenian (western)": "AM (Western)",
        "Asturian (Spain, with bottom-dot H and L)": "ES (Ast)",
        "Avatime": "GH (Avn)",
        "Azerbaijani": "AZ",
        "Azerbaijani (Cyrillic)": "AZ (Cyrillic)",
        "Azerbaijani (Iran)": "IR (Azb)",
        "Bambara": "ML",
        "Bangla": "BD",
        "Bangla (India, Baishakhi InScript)": "IN (Ben Inscript)",
        "Bangla (India, Baishakhi)": "IN (Ben Baishakhi)",
        "Bangla (India, Bornona)": "IN (Ben Bornona)",
        "Bangla (India, Gitanjali)": "IN (Ben Gitanjali)",
        "Bangla (India, Probhat)": "IN (Ben Probhat)",
        "Bangla (India)": "IN (Ben)",
        "Bangla (Probhat)": "BD (Probhat)",
        "Bashkirian": "RU (Bak)",
        "Belarusian": "BY",
        "Belarusian (intl.)": "BY (Intl)",
        "Belarusian (Latin)": "BY (Latin)",
        "Belarusian (legacy)": "BY (Legacy)",
        "Belarusian (phonetic)": "BY (Phonetic)",
        "Belgian": "BE",
        "Belgian (alt.)": "BE (Oss)",
        "Belgian (ISO, alt.)": "BE (Iso-Alternate)",
        "Belgian (Latin-9 only, alt.)": "BE (Oss Latin9)",
        "Belgian (no dead keys)": "BE (Nodeadkeys)",
        "Belgian (Wang 724 AZERTY)": "BE (Wang)",
        "Berber (Algeria, Latin)": "DZ",
        "Berber (Algeria, Tifinagh)": "DZ (Ber)",
        "Berber (Morocco, Tifinagh alt.)": "MA (Tifinagh-Alt)",
        "Berber (Morocco, Tifinagh extended phonetic)": "MA (Tifinagh-Extended-Phonetic)",
        "Berber (Morocco, Tifinagh extended)": "MA (Tifinagh-Extended)",
        "Berber (Morocco, Tifinagh phonetic, alt.)": "MA (Tifinagh-Alt-Phonetic)",
        "Berber (Morocco, Tifinagh phonetic)": "MA (Tifinagh-Phonetic)",
        "Berber (Morocco, Tifinagh)": "MA (Tifinagh)",
        "Bosnian": "BA",
        "Bosnian (US, with Bosnian digraphs)": "BA (Unicodeus)",
        "Bosnian (US)": "BA (Us)",
        "Bosnian (with Bosnian digraphs)": "BA (Unicode)",
        "Bosnian (with guillemets)": "BA (Alternatequotes)",
        "Braille": "BRAI",
        "Braille (left-handed inverted thumb)": "BRAI (Left Hand Invert)",
        "Braille (left-handed)": "BRAI (Left Hand)",
        "Braille (right-handed inverted thumb)": "BRAI (Right Hand Invert)",
        "Braille (right-handed)": "BRAI (Right Hand)",
        "Breton (France)": "FR (Bre)",
        "Bulgarian": "BG",
        "Bulgarian (enhanced)": "BG (Bekl)",
        "Bulgarian (new phonetic)": "BG (Bas Phonetic)",
        "Bulgarian (traditional phonetic)": "BG (Phonetic)",
        "Burmese": "MM",
        "Burmese Zawgyi": "MM (Zawgyi)",
        "Cameroon (AZERTY, intl.)": "CM (Azerty)",
        "Cameroon (Dvorak, intl.)": "CM (Dvorak)",
        "Cameroon Multilingual (QWERTY, intl.)": "CM (Qwerty)",
        "Canadian (CSA)": "CA (Multix)",
        "Catalan (Spain, with middle-dot L)": "ES (Cat)",
        "Cherokee": "US (Chr)",
        "Chinese": "CN",
        "Chuvash": "RU (Cv)",
        "Chuvash (Latin)": "RU (Cv Latin)",
        "CloGaelach": "IE (CloGaelach)",
        "Crimean Tatar (Turkish Alt-Q)": "UA (Crh Alt)",
        "Crimean Tatar (Turkish F)": "UA (Crh F)",
        "Crimean Tatar (Turkish Q)": "UA (Crh)",
        "Croatian": "HR",
        "Croatian (US, with Croatian digraphs)": "HR (Unicodeus)",
        "Croatian (US)": "HR (Us)",
        "Croatian (with Croatian digraphs)": "HR (Unicode)",
        "Croatian (with guillemets)": "HR (Alternatequotes)",
        "Czech": "CZ",
        "Czech (QWERTY, extended backslash)": "CZ (Qwerty Bksl)",
        "Czech (QWERTY, Macintosh)": "CZ (Qwerty-Mac)",
        "Czech (QWERTY)": "CZ (Qwerty)",
        "Czech (UCW, only accented letters)": "CZ (Ucw)",
        "Czech (US, Dvorak, UCW support)": "CZ (Dvorak-Ucw)",
        "Czech (with <\\|> key)": "CZ (Bksl)",
        "Danish": "DK",
        "Danish (Dvorak)": "DK (Dvorak)",
        "Danish (Macintosh, no dead keys)": "DK (Mac Nodeadkeys)",
        "Danish (Macintosh)": "DK (Mac)",
        "Danish (no dead keys)": "DK (Nodeadkeys)",
        "Danish (Windows)": "DK (Winkeys)",
        "Dari": "AF",
        "Dari (Afghanistan, OLPC)": "AF (Fa-Olpc)",
        "Dhivehi": "MV",
        "Dutch": "NL",
        "Dutch (Macintosh)": "NL (Mac)",
        "Dutch (standard)": "NL (Std)",
        "Dutch (US)": "NL (Us)",
        "Dzongkha": "BT",
        "English (Australian)": "AU",
        "English (Cameroon)": "CM",
        "English (Canada)": "CA (Eng)",
        "English (classic Dvorak)": "US (Dvorak-Classic)",
        "English (Colemak-DH ISO)": "US (Colemak Dh Iso)",
        "English (Colemak-DH)": "US (Colemak Dh)",
        "English (Colemak)": "US (Colemak)",
        "English (Dvorak, alt. intl.)": "US (Dvorak-Alt-Intl)",
        "English (Dvorak, intl., with dead keys)": "US (Dvorak-Intl)",
        "English (Dvorak, left-handed)": "US (Dvorak-L)",
        "English (Dvorak, Macintosh)": "US (Dvorak-Mac)",
        "English (Dvorak, right-handed)": "US (Dvorak-R)",
        "English (Dvorak)": "US (Dvorak)",
        "English (Ghana, GILLBT)": "GH (Gillbt)",
        "English (Ghana, multilingual)": "GH (Generic)",
        "English (Ghana)": "GH",
        "English (India, with rupee)": "IN (Eng)",
        "English (intl., with AltGr dead keys)": "US (Altgr-Intl)",
        "English (Macintosh)": "US (Mac)",
        "English (Mali, US, intl.)": "ML (Us-Intl)",
        "English (Mali, US, Macintosh)": "ML (Us-Mac)",
        "English (Nigeria)": "NG",
        "English (Norman)": "US (Norman)",
        "English (programmer Dvorak)": "US (Dvp)",
        "English (South Africa)": "ZA",
        "English (the divide/multiply toggle the layout)": "US (Olpc2)",
        "English (UK, Colemak-DH)": "GB (Colemak Dh)",
        "English (UK, Colemak)": "GB (Colemak)",
        "English (UK, Dvorak, with UK punctuation)": "GB (Dvorakukp)",
        "English (UK, Dvorak)": "GB (Dvorak)",
        "English (UK, extended, Windows)": "GB (Extd)",
        "English (UK, intl., with dead keys)": "GB (Intl)",
        "English (UK, Macintosh, intl.)": "GB (Mac Intl)",
        "English (UK, Macintosh)": "GB (Mac)",
        "English (UK)": "GB",
        "English (US, alt. intl.)": "US (Alt-Intl)",
        "English (US, euro on 5)": "US (Euro)",
        "English (US, intl., with dead keys)": "US (Intl)",
        "English (US, Symbolic)": "US (Symbolic)",
        "English (US)": "US",
        "English (Workman, intl., with dead keys)": "US (Workman-Intl)",
        "English (Workman)": "US (Workman)",
        "Esperanto": "EPO",
        "Esperanto (Brazil, Nativo)": "BR (Nativo-Epo)",
        "Esperanto (legacy)": "EPO (Legacy)",
        "Esperanto (Portugal, Nativo)": "PT (Nativo-Epo)",
        "Estonian": "EE",
        "Estonian (Dvorak)": "EE (Dvorak)",
        "Estonian (no dead keys)": "EE (Nodeadkeys)",
        "Estonian (US)": "EE (Us)",
        "Ewe": "GH (Ewe)",
        "Faroese": "FO",
        "Faroese (no dead keys)": "FO (Nodeadkeys)",
        "Filipino": "PH",
        "Filipino (Capewell-Dvorak, Baybayin)": "PH (Capewell-Dvorak-Bay)",
        "Filipino (Capewell-Dvorak, Latin)": "PH (Capewell-Dvorak)",
        "Filipino (Capewell-QWERF 2006, Baybayin)": "PH (Capewell-Qwerf2k6-Bay)",
        "Filipino (Capewell-QWERF 2006, Latin)": "PH (Capewell-Qwerf2k6)",
        "Filipino (Colemak, Baybayin)": "PH (Colemak-Bay)",
        "Filipino (Colemak, Latin)": "PH (Colemak)",
        "Filipino (Dvorak, Baybayin)": "PH (Dvorak-Bay)",
        "Filipino (Dvorak, Latin)": "PH (Dvorak)",
        "Filipino (QWERTY, Baybayin)": "PH (Qwerty-Bay)",
        "Finnish": "FI",
        "Finnish (classic, no dead keys)": "FI (Nodeadkeys)",
        "Finnish (classic)": "FI (Classic)",
        "Finnish (Macintosh)": "FI (Mac)",
        "Finnish (Windows)": "FI (Winkeys)",
        "French": "FR",
        "French (alt., Latin-9 only)": "FR (Oss Latin9)",
        "French (alt., no dead keys)": "FR (Oss Nodeadkeys)",
        "French (alt.)": "FR (Oss)",
        "French (AZERTY, AFNOR)": "FR (Afnor)",
        "French (AZERTY)": "FR (Azerty)",
        "French (BEPO, AFNOR)": "FR (Bepo Afnor)",
        "French (BEPO, Latin-9 only)": "FR (Bepo Latin9)",
        "French (BEPO)": "FR (Bepo)",
        "French (Cameroon)": "CM (French)",
        "French (Canada, Dvorak)": "CA (Fr-Dvorak)",
        "French (Canada, legacy)": "CA (Fr-Legacy)",
        "French (Canada)": "CA",
        "French (Democratic Republic of the Congo)": "CD",
        "French (Dvorak)": "FR (Dvorak)",
        "French (legacy, alt., no dead keys)": "FR (Latin9 Nodeadkeys)",
        "French (legacy, alt.)": "FR (Latin9)",
        "French (Macintosh)": "FR (Mac)",
        "French (Mali, alt.)": "ML (Fr-Oss)",
        "French (Morocco)": "MA (French)",
        "French (no dead keys)": "FR (Nodeadkeys)",
        "French (Switzerland, Macintosh)": "CH (Fr Mac)",
        "French (Switzerland, no dead keys)": "CH (Fr Nodeadkeys)",
        "French (Switzerland)": "CH (Fr)",
        "French (Togo)": "TG",
        "French (US)": "FR (Us)",
        "Friulian (Italy)": "IT (Fur)",
        "Fula": "GH (Fula)",
        "Ga": "GH (Ga)",
        "Georgian": "GE",
        "Georgian (ergonomic)": "GE (Ergonomic)",
        "Georgian (France, AZERTY Tskapo)": "FR (Geo)",
        "Georgian (Italy)": "IT (Geo)",
        "Georgian (MESS)": "GE (Mess)",
        "German": "DE",
        "German (Austria, Macintosh)": "AT (Mac)",
        "German (Austria, no dead keys)": "AT (Nodeadkeys)",
        "German (Austria)": "AT",
        "German (dead acute)": "DE (Deadacute)",
        "German (dead grave acute)": "DE (Deadgraveacute)",
        "German (dead tilde)": "DE (Deadtilde)",
        "German (Dvorak)": "DE (Dvorak)",
        "German (E1)": "DE (E1)",
        "German (E2)": "DE (E2)",
        "German (Macintosh, no dead keys)": "DE (Mac Nodeadkeys)",
        "German (Macintosh)": "DE (Mac)",
        "German (Neo 2)": "DE (Neo)",
        "German (no dead keys)": "DE (Nodeadkeys)",
        "German (QWERTY)": "DE (Qwerty)",
        "German (Switzerland, legacy)": "CH (Legacy)",
        "German (Switzerland, Macintosh)": "CH (De Mac)",
        "German (Switzerland, no dead keys)": "CH (De Nodeadkeys)",
        "German (Switzerland)": "CH",
        "German (T3)": "DE (T3)",
        "German (US)": "DE (Us)",
        "Greek": "GR",
        "Greek (extended)": "GR (Extended)",
        "Greek (no dead keys)": "GR (Nodeadkeys)",
        "Greek (polytonic)": "GR (Polytonic)",
        "Greek (simple)": "GR (Simple)",
        "Gujarati": "IN (Guj)",
        "Hanyu Pinyin Letters (with AltGr dead keys)": "CN (Altgr-Pinyin)",
        "Hausa (Ghana)": "GH (Hausa)",
        "Hausa (Nigeria)": "NG (Hausa)",
        "Hawaiian": "US (Haw)",
        "Hebrew": "IL",
        "Hebrew (Biblical, Tiro)": "IL (Biblical)",
        "Hebrew (lyx)": "IL (Lyx)",
        "Hebrew (phonetic)": "IL (Phonetic)",
        "Hindi (Bolnagri)": "IN (Bolnagri)",
        "Hindi (KaGaPa, phonetic)": "IN (Hin-Kagapa)",
        "Hindi (Wx)": "IN (Hin-Wx)",
        "Hungarian": "HU",
        "Hungarian (no dead keys)": "HU (Nodeadkeys)",
        "Hungarian (QWERTY, 101-key, comma, dead keys)": "HU (101 Qwerty Comma Dead)",
        "Hungarian (QWERTY, 101-key, comma, no dead keys)": "HU (101 Qwerty Comma Nodead)",
        "Hungarian (QWERTY, 101-key, dot, dead keys)": "HU (101 Qwerty Dot Dead)",
        "Hungarian (QWERTY, 101-key, dot, no dead keys)": "HU (101 Qwerty Dot Nodead)",
        "Hungarian (QWERTY, 102-key, comma, dead keys)": "HU (102 Qwerty Comma Dead)",
        "Hungarian (QWERTY, 102-key, comma, no dead keys)": "HU (102 Qwerty Comma Nodead)",
        "Hungarian (QWERTY, 102-key, dot, dead keys)": "HU (102 Qwerty Dot Dead)",
        "Hungarian (QWERTY, 102-key, dot, no dead keys)": "HU (102 Qwerty Dot Nodead)",
        "Hungarian (QWERTY)": "HU (Qwerty)",
        "Hungarian (QWERTZ, 101-key, comma, dead keys)": "HU (101 Qwertz Comma Dead)",
        "Hungarian (QWERTZ, 101-key, comma, no dead keys)": "HU (101 Qwertz Comma Nodead)",
        "Hungarian (QWERTZ, 101-key, dot, dead keys)": "HU (101 Qwertz Dot Dead)",
        "Hungarian (QWERTZ, 101-key, dot, no dead keys)": "HU (101 Qwertz Dot Nodead)",
        "Hungarian (QWERTZ, 102-key, comma, dead keys)": "HU (102 Qwertz Comma Dead)",
        "Hungarian (QWERTZ, 102-key, comma, no dead keys)": "HU (102 Qwertz Comma Nodead)",
        "Hungarian (QWERTZ, 102-key, dot, dead keys)": "HU (102 Qwertz Dot Dead)",
        "Hungarian (QWERTZ, 102-key, dot, no dead keys)": "HU (102 Qwertz Dot Nodead)",
        "Hungarian (standard)": "HU (Standard)",
        "Icelandic": "IS",
        "Icelandic (Dvorak)": "IS (Dvorak)",
        "Icelandic (Macintosh, legacy)": "IS (Mac Legacy)",
        "Icelandic (Macintosh)": "IS (Mac)",
        "Igbo": "NG (Igbo)",
        "Indian": "IN",
        "Indic IPA": "IN (Iipa)",
        "Indonesian (Arab Melayu, extended phonetic)": "ID (Melayu-Phoneticx)",
        "Indonesian (Arab Melayu, phonetic)": "ID (Melayu-Phonetic)",
        "Indonesian (Arab Pegon, phonetic)": "ID (Pegon-Phonetic)",
        "Indonesian (Latin)": "ID",
        "Inuktitut": "CA (Ike)",
        "Iraqi": "IQ",
        "Irish": "IE",
        "Irish (UnicodeExpert)": "IE (UnicodeExpert)",
        "Italian": "IT",
        "Italian (IBM 142)": "IT (Ibm)",
        "Italian (intl., with dead keys)": "IT (Intl)",
        "Italian (Macintosh)": "IT (Mac)",
        "Italian (no dead keys)": "IT (Nodeadkeys)",
        "Italian (US)": "IT (Us)",
        "Italian (Windows)": "IT (Winkeys)",
        "Japanese": "JP",
        "Japanese (Dvorak)": "JP (Dvorak)",
        "Japanese (Kana 86)": "JP (Kana86)",
        "Japanese (Kana)": "JP (Kana)",
        "Japanese (Macintosh)": "JP (Mac)",
        "Japanese (OADG 109A)": "JP (OADG109A)",
        "Javanese": "ID (Javanese)",
        "Kabyle (AZERTY, with dead keys)": "DZ (Azerty-Deadkeys)",
        "Kabyle (QWERTY, UK, with dead keys)": "DZ (Qwerty-Gb-Deadkeys)",
        "Kabyle (QWERTY, US, with dead keys)": "DZ (Qwerty-Us-Deadkeys)",
        "Kalmyk": "RU (Xal)",
        "Kannada": "IN (Kan)",
        "Kannada (KaGaPa, phonetic)": "IN (Kan-Kagapa)",
        "Kashubian": "PL (Csb)",
        "Kazakh": "KZ",
        "Kazakh (extended)": "KZ (Ext)",
        "Kazakh (Latin)": "KZ (Latin)",
        "Kazakh (with Russian)": "KZ (Kazrus)",
        "Khmer (Cambodia)": "KH",
        "Kikuyu": "KE (Kik)",
        "Komi": "RU (Kom)",
        "Korean": "KR",
        "Korean (101/104-key compatible)": "KR (Kr104)",
        "Kurdish (Iran, Arabic-Latin)": "IR (Ku Ara)",
        "Kurdish (Iran, F)": "IR (Ku F)",
        "Kurdish (Iran, Latin Alt-Q)": "IR (Ku Alt)",
        "Kurdish (Iran, Latin Q)": "IR (Ku)",
        "Kurdish (Iraq, Arabic-Latin)": "IQ (Ku Ara)",
        "Kurdish (Iraq, F)": "IQ (Ku F)",
        "Kurdish (Iraq, Latin Alt-Q)": "IQ (Ku Alt)",
        "Kurdish (Iraq, Latin Q)": "IQ (Ku)",
        "Kurdish (Syria, F)": "SY (Ku F)",
        "Kurdish (Syria, Latin Alt-Q)": "SY (Ku Alt)",
        "Kurdish (Syria, Latin Q)": "SY (Ku)",
        "Kurdish (Turkey, F)": "TR (Ku F)",
        "Kurdish (Turkey, Latin Alt-Q)": "TR (Ku Alt)",
        "Kurdish (Turkey, Latin Q)": "TR (Ku)",
        "Kyrgyz": "KG",
        "Kyrgyz (phonetic)": "KG (Phonetic)",
        "Lao": "LA",
        "Lao (STEA)": "LA (Stea)",
        "Latvian": "LV",
        "Latvian (adapted)": "LV (Adapted)",
        "Latvian (apostrophe)": "LV (Apostrophe)",
        "Latvian (ergonomic)": "LV (Ergonomic)",
        "Latvian (F)": "LV (Fkey)",
        "Latvian (modern)": "LV (Modern)",
        "Latvian (tilde)": "LV (Tilde)",
        "Lithuanian": "LT",
        "Lithuanian (IBM LST 1205-92)": "LT (Ibm)",
        "Lithuanian (LEKP)": "LT (Lekp)",
        "Lithuanian (LEKPa)": "LT (Lekpa)",
        "Lithuanian (Ratise)": "LT (Ratise)",
        "Lithuanian (standard)": "LT (Std)",
        "Lithuanian (US)": "LT (Us)",
        "Lower Sorbian": "DE (Dsb)",
        "Lower Sorbian (QWERTZ)": "DE (Dsb Qwertz)",
        "Macedonian": "MK",
        "Macedonian (no dead keys)": "MK (Nodeadkeys)",
        "Malay (Jawi, Arabic Keyboard)": "MY",
        "Malay (Jawi, phonetic)": "MY (Phonetic)",
        "Malayalam": "IN (Mal)",
        "Malayalam (enhanced InScript, with rupee)": "IN (Mal Enhanced)",
        "Malayalam (Lalitha)": "IN (Mal Lalitha)",
        "Maltese": "MT",
        "Maltese (UK, with AltGr overrides)": "MT (Alt-Gb)",
        "Maltese (US, with AltGr overrides)": "MT (Alt-Us)",
        "Maltese (US)": "MT (Us)",
        "Manipuri (Eeyek)": "IN (Eeyek)",
        "Maori": "MAO",
        "Marathi (enhanced InScript)": "IN (Marathi)",
        "Marathi (KaGaPa, phonetic)": "IN (Mar-Kagapa)",
        "Mari": "RU (Chm)",
        "Mmuock": "CM (Mmuock)",
        "Moldavian": "MD",
        "Moldavian (Gagauz)": "MD (Gag)",
        "Mon": "MM (Mnw)",
        "Mon (A1)": "MM (Mnw-A1)",
        "Mongolian": "MN",
        "Mongolian (Bichig)": "CN (Mon Trad)",
        "Mongolian (Galik)": "CN (Mon Trad Galik)",
        "Mongolian (Manchu Galik)": "CN (Mon Manchu Galik)",
        "Mongolian (Manchu)": "CN (Mon Trad Manchu)",
        "Mongolian (Todo Galik)": "CN (Mon Todo Galik)",
        "Mongolian (Todo)": "CN (Mon Trad Todo)",
        "Mongolian (Xibe)": "CN (Mon Trad Xibe)",
        "Montenegrin": "ME",
        "Montenegrin (Cyrillic, with guillemets)": "ME (Cyrillicalternatequotes)",
        "Montenegrin (Cyrillic, ZE and ZHE swapped)": "ME (Cyrillicyz)",
        "Montenegrin (Cyrillic)": "ME (Cyrillic)",
        "Montenegrin (Latin, QWERTY)": "ME (Latinyz)",
        "Montenegrin (Latin, Unicode, QWERTY)": "ME (Latinunicodeyz)",
        "Montenegrin (Latin, Unicode)": "ME (Latinunicode)",
        "Montenegrin (Latin, with guillemets)": "ME (Latinalternatequotes)",
        "N'Ko (AZERTY)": "GN",
        "Nepali": "NP",
        "Northern Saami (Finland)": "FI (Smi)",
        "Northern Saami (Norway, no dead keys)": "NO (Smi Nodeadkeys)",
        "Northern Saami (Norway)": "NO (Smi)",
        "Northern Saami (Sweden)": "SE (Smi)",
        "Norwegian": "NO",
        "Norwegian (Colemak)": "NO (Colemak)",
        "Norwegian (Dvorak)": "NO (Dvorak)",
        "Norwegian (Macintosh, no dead keys)": "NO (Mac Nodeadkeys)",
        "Norwegian (Macintosh)": "NO (Mac)",
        "Norwegian (no dead keys)": "NO (Nodeadkeys)",
        "Norwegian (Windows)": "NO (Winkeys)",
        "Occitan": "FR (Oci)",
        "Ogham": "IE (Ogam)",
        "Ogham (IS434)": "IE (Ogam Is434)",
        "Ol Chiki": "IN (Olck)",
        "Old Turkic": "TR (Otk)",
        "Old Turkic (F)": "TR (Otkf)",
        "Oriya": "IN (Ori)",
        "Oriya (Bolnagri)": "IN (Ori-Bolnagri)",
        "Oriya (Wx)": "IN (Ori-Wx)",
        "Ossetian (Georgia)": "GE (Os)",
        "Ossetian (legacy)": "RU (Os Legacy)",
        "Ossetian (Windows)": "RU (Os Winkeys)",
        "Ottoman (F)": "TR (Otf)",
        "Ottoman (Q)": "TR (Ot)",
        "Pannonian Rusyn": "RS (Rue)",
        "Pashto": "AF (Ps)",
        "Pashto (Afghanistan, OLPC)": "AF (Ps-Olpc)",
        "Persian": "IR",
        "Persian (with Persian keypad)": "IR (Pes Keypad)",
        "Polish": "PL",
        "Polish (British keyboard)": "GB (Pl)",
        "Polish (Dvorak, with Polish quotes on key 1)": "PL (Dvorak Altquotes)",
        "Polish (Dvorak, with Polish quotes on quotemark key)": "PL (Dvorak Quotes)",
        "Polish (Dvorak)": "PL (Dvorak)",
        "Polish (legacy)": "PL (Legacy)",
        "Polish (programmer Dvorak)": "PL (Dvp)",
        "Polish (QWERTZ)": "PL (Qwertz)",
        "Portuguese": "PT",
        "Portuguese (Brazil, Dvorak)": "BR (Dvorak)",
        "Portuguese (Brazil, IBM/Lenovo ThinkPad)": "BR (Thinkpad)",
        "Portuguese (Brazil, Nativo for US keyboards)": "BR (Nativo-Us)",
        "Portuguese (Brazil, Nativo)": "BR (Nativo)",
        "Portuguese (Brazil, no dead keys)": "BR (Nodeadkeys)",
        "Portuguese (Brazil)": "BR",
        "Portuguese (Macintosh, no dead keys)": "PT (Mac Nodeadkeys)",
        "Portuguese (Macintosh)": "PT (Mac)",
        "Portuguese (Nativo for US keyboards)": "PT (Nativo-Us)",
        "Portuguese (Nativo)": "PT (Nativo)",
        "Portuguese (no dead keys)": "PT (Nodeadkeys)",
        "Punjabi (Gurmukhi Jhelum)": "IN (Jhelum)",
        "Punjabi (Gurmukhi)": "IN (Guru)",
        "Romanian": "RO",
        "Romanian (Germany, no dead keys)": "DE (Ro Nodeadkeys)",
        "Romanian (Germany)": "DE (Ro)",
        "Romanian (standard)": "RO (Std)",
        "Romanian (Windows)": "RO (Winkeys)",
        "Russian": "RU",
        "Russian (Belarus)": "BY (Ru)",
        "Russian (Czech, phonetic)": "CZ (Rus)",
        "Russian (DOS)": "RU (Dos)",
        "Russian (engineering, EN)": "RU (Ruchey En)",
        "Russian (engineering, RU)": "RU (Ruchey Ru)",
        "Russian (Georgia)": "GE (Ru)",
        "Russian (Germany, phonetic)": "DE (Ru)",
        "Russian (Kazakhstan, with Kazakh)": "KZ (Ruskaz)",
        "Russian (legacy)": "RU (Legacy)",
        "Russian (Macintosh)": "RU (Mac)",
        "Russian (phonetic, AZERTY)": "RU (Phonetic Azerty)",
        "Russian (phonetic, Dvorak)": "RU (Phonetic Dvorak)",
        "Russian (phonetic, French)": "RU (Phonetic Fr)",
        "Russian (phonetic, Windows)": "RU (Phonetic Winkeys)",
        "Russian (phonetic, YAZHERTY)": "RU (Phonetic YAZHERTY)",
        "Russian (phonetic)": "RU (Phonetic)",
        "Russian (Poland, phonetic Dvorak)": "PL (Ru Phonetic Dvorak)",
        "Russian (Sweden, phonetic, no dead keys)": "SE (Rus Nodeadkeys)",
        "Russian (Sweden, phonetic)": "SE (Rus)",
        "Russian (typewriter, legacy)": "RU (Typewriter-Legacy)",
        "Russian (typewriter)": "RU (Typewriter)",
        "Russian (Ukraine, standard RSTU)": "UA (Rstu Ru)",
        "Russian (US, phonetic)": "US (Rus)",
        "Saisiyat (Taiwan)": "TW (Saisiyat)",
        "Samogitian": "LT (Sgs)",
        "Sanskrit (KaGaPa, phonetic)": "IN (San-Kagapa)",
        "Scottish Gaelic": "GB (Gla)",
        "Serbian": "RS",
        "Serbian (Cyrillic, with guillemets)": "RS (Alternatequotes)",
        "Serbian (Cyrillic, ZE and ZHE swapped)": "RS (Yz)",
        "Serbian (Latin, QWERTY)": "RS (Latinyz)",
        "Serbian (Latin, Unicode, QWERTY)": "RS (Latinunicodeyz)",
        "Serbian (Latin, Unicode)": "RS (Latinunicode)",
        "Serbian (Latin, with guillemets)": "RS (Latinalternatequotes)",
        "Serbian (Latin)": "RS (Latin)",
        "Serbian (Russia)": "RU (Srp)",
        "Serbo-Croatian (US)": "US (Hbs)",
        "Shan": "MM (Shn)",
        "Shan (Zawgyi Tai)": "MM (Zgt)",
        "Sicilian": "IT (Scn)",
        "Silesian": "PL (Szl)",
        "Sindhi": "PK (Snd)",
        "Sinhala (phonetic)": "LK",
        "Sinhala (US)": "LK (Us)",
        "Slovak": "SK",
        "Slovak (extended backslash)": "SK (Bksl)",
        "Slovak (QWERTY, extended backslash)": "SK (Qwerty Bksl)",
        "Slovak (QWERTY)": "SK (Qwerty)",
        "Slovenian": "SI",
        "Slovenian (US)": "SI (Us)",
        "Slovenian (with guillemets)": "SI (Alternatequotes)",
        "Spanish": "ES",
        "Spanish (dead tilde)": "ES (Deadtilde)",
        "Spanish (Dvorak)": "ES (Dvorak)",
        "Spanish (Latin American, Colemak)": "LATAM (Colemak)",
        "Spanish (Latin American, dead tilde)": "LATAM (Deadtilde)",
        "Spanish (Latin American, Dvorak)": "LATAM (Dvorak)",
        "Spanish (Latin American, no dead keys)": "LATAM (Nodeadkeys)",
        "Spanish (Latin American)": "LATAM",
        "Spanish (Macintosh)": "ES (Mac)",
        "Spanish (no dead keys)": "ES (Nodeadkeys)",
        "Spanish (Windows)": "ES (Winkeys)",
        "Swahili (Kenya)": "KE",
        "Swahili (Tanzania)": "TZ",
        "Swedish": "SE",
        "Swedish (Dvorak, intl.)": "SE (Us Dvorak)",
        "Swedish (Dvorak)": "SE (Dvorak)",
        "Swedish (Macintosh)": "SE (Mac)",
        "Swedish (no dead keys)": "SE (Nodeadkeys)",
        "Swedish (Svdvorak)": "SE (Svdvorak)",
        "Swedish (US)": "SE (Us)",
        "Swedish Sign Language": "SE (Swl)",
        "Syriac": "SY (Syc)",
        "Syriac (phonetic)": "SY (Syc Phonetic)",
        "Taiwanese": "TW",
        "Taiwanese (indigenous)": "TW (Indigenous)",
        "Tajik": "TJ",
        "Tajik (legacy)": "TJ (Legacy)",
        "Tamil (InScript, with Arabic numerals)": "IN (Tam)",
        "Tamil (InScript, with Tamil numerals)": "IN (Tam Tamilnumbers)",
        "Tamil (Sri Lanka, TamilNet '99, TAB encoding)": "LK (Tam TAB)",
        "Tamil (Sri Lanka, TamilNet '99)": "LK (Tam Unicode)",
        "Tamil (TamilNet '99 with Tamil numerals)": "IN (Tamilnet Tamilnumbers)",
        "Tamil (TamilNet '99, TAB encoding)": "IN (Tamilnet TAB)",
        "Tamil (TamilNet '99, TSCII encoding)": "IN (Tamilnet TSCII)",
        "Tamil (TamilNet '99)": "IN (Tamilnet)",
        "Tarifit": "MA (Rif)",
        "Tatar": "RU (Tt)",
        "Telugu": "IN (Tel)",
        "Telugu (KaGaPa, phonetic)": "IN (Tel-Kagapa)",
        "Telugu (Sarala)": "IN (Tel-Sarala)",
        "Thai": "TH",
        "Thai (Pattachote)": "TH (Pat)",
        "Thai (TIS-820.2538)": "TH (Tis)",
        "Tibetan": "CN (Tib)",
        "Tibetan (with ASCII numerals)": "CN (Tib Asciinum)",
        "Tswana": "BW",
        "Turkish": "TR",
        "Turkish (Alt-Q)": "TR (Alt)",
        "Turkish (E)": "TR (E)",
        "Turkish (F)": "TR (F)",
        "Turkish (Germany)": "DE (Tr)",
        "Turkish (intl., with dead keys)": "TR (Intl)",
        "Turkmen": "TM",
        "Turkmen (Alt-Q)": "TM (Alt)",
        "Udmurt": "RU (Udm)",
        "Ukrainian": "UA",
        "Ukrainian (homophonic)": "UA (Homophonic)",
        "Ukrainian (legacy)": "UA (Legacy)",
        "Ukrainian (macOS)": "UA (MacOS)",
        "Ukrainian (phonetic)": "UA (Phonetic)",
        "Ukrainian (standard RSTU)": "UA (Rstu)",
        "Ukrainian (typewriter)": "UA (Typewriter)",
        "Ukrainian (Windows)": "UA (Winkeys)",
        "Urdu (alt. phonetic)": "IN (Urd-Phonetic3)",
        "Urdu (Pakistan, CRULP)": "PK (Urd-Crulp)",
        "Urdu (Pakistan, NLA)": "PK (Urd-Nla)",
        "Urdu (Pakistan)": "PK",
        "Urdu (phonetic)": "IN (Urd-Phonetic)",
        "Urdu (Windows)": "IN (Urd-Winkeys)",
        "Uyghur": "CN (Ug)",
        "Uzbek": "UZ",
        "Uzbek (Afghanistan, OLPC)": "AF (Uz-Olpc)",
        "Uzbek (Afghanistan)": "AF (Uz)",
        "Uzbek (Latin)": "UZ (Latin)",
        "Vietnamese": "VN",
        "Vietnamese (France)": "VN (Fr)",
        "Vietnamese (US)": "VN (Us)",
        "Wolof": "SN",
        "Yakut": "RU (Sah)",
        "Yoruba": "NG (Yoruba)",
        "Unknown Layout": "Unknown",
    }


WINDOW_TITLE_MAP = [
    # Original Entries
    ["rofi", "", "Rofi"],
    # Browsers
    ["google-chrome", "", "Google Chrome"],
    ["brave-browser", "󰖟", "Brave Browser"],
    ["firefox", "󰈹", "Firefox"],
    ["microsoft-edge", "󰇩", "Edge"],
    ["chromium", "", "Chromium"],
    ["opera", "", "Opera"],
    ["vivaldi", "󰖟", "Vivaldi"],
    ["librefox", "󰖟", "Librefox"],
    ["waterfox", "󰖟", "Waterfox"],
    ["zen", "󰖟", "Zen Browser"],
    ["thorium", "󰖟", "Thorium"],
    ["tor-browser", "", "Tor Browser"],
    ["floorp", "󰈹", "Floorp"],
    # Terminals
    ["gnome-terminal", "", "GNOME Terminal"],
    ["kitty", "󰄛", "Kitty Terminal"],
    ["konsole", "", "Konsole"],
    ["alacritty", "", "Alacritty"],
    ["wezterm", "", "Wezterm"],
    ["foot", "󰽒", "Foot Terminal"],
    ["tilix", "", "Tilix"],
    ["xterm", "", "XTerm"],
    ["urxvt", "", "URxvt"],
    ["st", "", "st Terminal"],
    ["com.mitchellh.ghostty", "󰊠", "Ghostty"],
    # Development Tools
    ["docker", "", "Docker"],
    ["emacs", "", "Emacs"],
    ["cursor", "󰨞", "Cursor"],
    ["vscode", "󰨞", "VS Code"],
    ["code", "󰨞", "VS Code"],
    ["sublime-text", "", "Sublime Text"],
    ["atom", "", "Atom"],
    ["android-studio", "󰀴", "Android Studio"],
    ["jetbrains-idea", "", "IntelliJ IDEA"],
    ["jetbrains-pycharm", "󱃖", "PyCharm"],
    ["jetbrains-webstorm", "󱃖", "WebStorm"],
    ["zed", "󱃖", "Zed"],
    ["jetbrains-phpstorm", "󱃖", "PhpStorm"],
    ["Postman", "󱃖", "Postman"],
    ["eclipse", "", "Eclipse"],
    ["netbeans", "", "NetBeans"],
    ["vim", "", "Vim"],
    ["neovim", "", "Neovim"],
    ["neovide", "", "Neovide"],
    ["emacs", "", "Emacs"],
    # Communication Tools
    ["slack", "󰒱", "Slack"],
    ["telegram-desktop", "", "Telegram"],
    ["org.telegram.desktop", "", "Telegram"],
    ["whatsapp", "󰖣", "WhatsApp"],
    ["teams", "󰊻", "Microsoft Teams"],
    ["teamspeak", "", "TeamSpeak"],
    ["skype", "󰒯", "Skype"],
    ["thunderbird", "", "Thunderbird"],
    ["discord", "", "Discord"],
    ["vesktop", "", "Vesktop"],
    ["legcord", "", "Legcord"],
    ["webcord", "", "WebCord"],
    # File Managers
    ["org.kde.dolphin", "", "Dolphin"],
    ["nautilus", "󰝰", "Files (Nautilus)"],
    ["thunar", "󰝰", "Thunar"],
    ["pcmanfm", "󰝰", "PCManFM"],
    ["nemo", "󰝰", "Nemo"],
    ["ranger", "󰝰", "Ranger"],
    ["doublecmd", "󰝰", "Double Commander"],
    ["krusader", "󰝰", "Krusader"],
    # Media Players
    ["vlc", "󰕼", "VLC Media Player"],
    ["mpv", "", "MPV"],
    ["rhythmbox", "󰓃", "Rhythmbox"],
    ["spotify", "󰓇", "Spotify"],
    ["spotube", "󰓇", "Spotify"],
    ["plex", "󰚺", "Plex"],
    ["ristretto", "󰋩", "Ristretto"],
    # Graphics Tools
    ["gimp", "", "GIMP"],
    ["inkscape", "", "Inkscape"],
    ["krita", "", "Krita"],
    ["blender", "󰂫", "Blender"],
    # Video Editing
    ["kdenlive", "", "Kdenlive"],
    # Games and Gaming Platforms
    ["steam", "", "Steam"],
    ["lutris", "󰺵", "Lutris"],
    ["heroic", "󰺵", "Heroic Games Launcher"],
    ["minecraft", "󰍳", "Minecraft"],
    ["csgo", "󰺵", "CS:GO"],
    ["dota2", "󰺵", "Dota 2"],
    # Office and Productivity
    ["evernote", "", "Evernote"],
    ["sioyek", "", "Sioyek"],
    ["libreoffice-base", "", "LibreOffice Base"],
    ["libreoffice-calc", "", "LibreOffice Calc"],
    ["libreoffice-draw", "", "LibreOffice Draw"],
    ["org.pwmt.zathura", "", "Zathura"],
    ["libreoffice-impress", "", "LibreOffice Impress"],
    ["libreoffice-math", "", "LibreOffice Math"],
    ["libreoffice-writer", "", "LibreOffice Writer"],
    ["obsidian", "󱓧", "Obsidian"],
    ["libreoffice", "", "LibreOffice Default"],
    ["title:LibreOffice", "", "LibreOffice Dialogs"],
    ["soffice", "", "LibreOffice Base Selector"],
    # Cloud Services and Sync
    ["dropbox", "󰇣", "Dropbox"],
    # cleanup and maintenance tools
    ["org.bleachbit.bleachbit", "", "BleachBit"],
    ["stacer", "", "Stacer"],
    # Desktop
    ["^$", "󰇄", "Desktop"],
]


# Updated set of named colors
NAMED_COLORS = frozenset(
    {
        "alice blue",
        "antique white",
        "aqua",
        "aquamarine",
        "azure",
        "beige",
        "bisque",
        "black",
        "blanched almond",
        "blue",
        "blue violet",
        "brown",
        "burlywood",
        "cadet blue",
        "chartreuse",
        "chocolate",
        "coral",
        "cornflower blue",
        "cornsilk",
        "crimson",
        "cyan",
        "dark blue",
        "dark cyan",
        "dark goldenrod",
        "dark gray",
        "dark green",
        "dark khaki",
        "dark magenta",
        "dark olive green",
        "dark orange",
        "dark orchid",
        "dark red",
        "dark salmon",
        "dark sea green",
        "dark slate blue",
        "dark slate gray",
        "dark turquoise",
        "dark violet",
        "deep pink",
        "deep sky blue",
        "dim gray",
        "dodger blue",
        "firebrick",
        "floral white",
        "forest green",
        "fuchsia",
        "gainsboro",
        "ghost white",
        "gold",
        "goldenrod",
        "gray",
        "green",
        "green yellow",
        "honeydew",
        "hot pink",
        "indian red",
        "indigo",
        "ivory",
        "khaki",
        "lavender",
        "lavender blush",
        "lawn green",
        "lemon chiffon",
        "light blue",
        "light coral",
        "light cyan",
        "light goldenrod yellow",
        "light green",
        "light grey",
        "light pink",
        "light salmon",
        "light sea green",
        "light sky blue",
        "light slate gray",
        "light steel blue",
        "light yellow",
        "lime",
        "lime green",
        "linen",
        "magenta",
        "maroon",
        "medium aquamarine",
        "medium blue",
        "medium orchid",
        "medium purple",
        "medium sea green",
        "medium slate blue",
        "medium spring green",
        "medium turquoise",
        "medium violet red",
        "midnight blue",
        "mint cream",
        "misty rose",
        "moccasin",
        "navajo white",
        "navy",
        "old lace",
        "olive",
        "olive drab",
        "orange",
        "orange red",
        "orchid",
        "pale goldenrod",
        "pale green",
        "pale turquoise",
        "pale violet red",
        "papaya whip",
        "peach puff",
        "peru",
        "pink",
        "plum",
        "powder blue",
        "purple",
        "red",
        "rosy brown",
        "royal blue",
        "saddle brown",
        "salmon",
        "sandy brown",
        "sea green",
        "seashell",
        "sienna",
        "silver",
        "sky blue",
        "slate blue",
        "slate gray",
        "snow",
        "spring green",
        "steel blue",
        "tan",
        "teal",
        "thistle",
        "tomato",
        "turquoise",
        "violet",
        "wheat",
        "white",
        "white smoke",
        "yellow",
        "yellow green",
    }
)

# Common regexes and small constant sets shared across modules
NEWLINE_RE = re.compile(r"\r?\n")

# Pre-compiled regex patterns for color validation
HEX_COLOR_RE = re.compile(r"^#(?:[a-fA-F0-9]{3,4}|[a-fA-F0-9]{6,8})$")
RGB_RE = re.compile(r"^rgb\(\s*(\d{1,3}%?\s*,\s*){2}\d{1,3}%?\s*\)$")
RGBA_RE = re.compile(r"^rgba\(\s*(\d{1,3}%?\s*,\s*){3}(0|1|0?\.\d+)\s*\)$")


# Suffixes used when normalizing application/window class names
NORMALIZE_SUFFIXES = frozenset((".bin", ".exe", ".so", "-bin", "-gtk"))


TEMP_PATHS = set()

# Pre-computed constants
SPECIAL_WIDGET_TYPES = frozenset(
    ("custom_button", "group", "collapsible", "custom_widget")
)
GROUP_TYPES = frozenset(("widget_groups", "collapsible_groups"))
URGENCY_LEVELS = frozenset(("low", "normal", "critical"))
BYTES_FACTORS = {"kb": 1, "mb": 2, "gb": 3, "tb": 4}
WHITE = (255, 255, 255)
