# ruff: noqa: E501

WEATHER_SYMBOL_WI_DAY = {
    "Unknown": "",
    "Cloudy": "",
    "Fog": "",
    "HeavyRain": "",
    "HeavyShowers": "",
    "HeavySnow": "",
    "HeavySnowShowers": "",
    "LightRain": "",
    "LightShowers": "",
    "LightSleet": "",
    "LightSleetShowers": "",
    "LightSnow": "",
    "LightSnowShowers": "",
    "PartlyCloudy": "",
    "Sunny": "",
    "ThunderyHeavyRain": "",
    "ThunderyShowers": "",
    "ThunderySnowShowers": "",
    "VeryCloudy": "",
}

WEATHER_SYMBOL_WI_NIGHT = {
    "Unknown": "",
    "Cloudy": "",
    "Fog": "",
    "HeavyRain": "",
    "HeavyShowers": "",
    "HeavySnow": "",
    "HeavySnowShowers": "",
    "LightRain": "",
    "LightShowers": "",
    "LightSleet": "",
    "LightSleetShowers": "",
    "LightSnow": "",
    "LightSnowShowers": "",
    "PartlyCloudy": "",
    "Sunny": "",
    "ThunderyHeavyRain": "",
    "ThunderyShowers": "",
    "ThunderySnowShowers": "",
    "VeryCloudy": "",
}

WEATHER_ICONS = {
    "113": {
        "description": "Sunny",
        "icon": WEATHER_SYMBOL_WI_DAY["Sunny"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Sunny"],
        "image": "clear-day",
        "image-night": "clear-night",
        "color": "#FFD24D",
        "quote": "It's a sunny day, gonna be fun! \nDon't go wandering all by yourself though",
    },
    "116": {
        "description": "PartlyCloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["PartlyCloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["PartlyCloudy"],
        "image": "partly-cloudy-day",
        "image-night": "partly-cloudy-night",
        "color": "#C4D7F2",
        "quote": "It's  cloudy, sort of gloomy \nYou'd better get a book to read",
    },
    "119": {
        "description": "Cloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["Cloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Cloudy"],
        "image": "cloudy",
        "image-night": "cloudy",
        "color": "#9CA3AF",
        "quote": "It's  cloudy, sort of gloomy \nYou'd better get a book to read",
    },
    "122": {
        "description": "VeryCloudy",
        "icon": WEATHER_SYMBOL_WI_DAY["VeryCloudy"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["VeryCloudy"],
        "image": "cloudy",
        "image-night": "cloudy",
        "color": "#6B7280",
        "quote": "It's  cloudy, sort of gloomy \nYou'd better get a book to read",
    },
    "143": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog-night",
        "color": "#CCD6E0",
        "quote": "Forecast says it's misty \nMake sure you don't get lost on your way",
    },
    "176": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#6BA4E2",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "179": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#91A8B6",
        "quote": "The forecast is vague; your day's still great!",
    },
    "182": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "The forecast is vague; your day's still great!",
    },
    "185": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "The forecast is vague; your day's still great!",
    },
    "200": {
        "description": "ThunderyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyShowers"],
        "image": "thunderstorms",
        "image-night": "thunderstorms-night",
        "color": "#5B6D7A",
        "quote": "There's storm for forecast today \nMake sure you don't get blown away",
    },
    "227": {
        "description": "LightSnow",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#DDE7F0",
        "quote": "It's snowing, it's a great day! \nGet some ramen and watch as the snow falls",
    },
    "230": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#E3EDF6",
        "quote": "It's gonna snow today \nYou'd better wear thick clothes and make a snowman as well!",
    },
    "248": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog",
        "color": "#CCD6E0",
        "quote": "Forecast says it's misty \nMake sure you don't get lost on your way",
    },
    "260": {
        "description": "Fog",
        "icon": WEATHER_SYMBOL_WI_DAY["Fog"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["Fog"],
        "image": "fog",
        "image-night": "fog-night",
        "color": "#CCD6E0",
        "quote": "Forecast says it's misty \nMake sure you don't get lost on your way",
    },
    "263": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#6BA4E2",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "266": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#5B8FD7",
        "quote": "When clouds cry, the earth drinks deep. A perfect day for promises to keep",
    },
    "281": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "The forecast is vague; your day's still great!",
    },
    "284": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "No clear forecast? Create your own sun.",
    },
    "293": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#5B8FD7",
        "quote": "When clouds cry, the earth drinks deep. A perfect day for promises to keep",
    },
    "296": {
        "description": "LightRain",
        "icon": WEATHER_SYMBOL_WI_DAY["LightRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#5B8FD7",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "299": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#4A6A8C",
        "quote": "When clouds cry, the earth drinks deep. A perfect day for promises to keep",
    },
    "302": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#405772",
        "quote": "Grey skies, cozy vibes. A gentle day, where calm truly thrives",
    },
    "305": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#4A6A8C",
        "quote": "The world is washing clean. A perfect excuse for dreams unseen",
    },
    "308": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#405772",
        "quote": "When clouds cry, the earth drinks deep. A perfect day for promises to keep",
    },
    "311": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "Weather's a wild card; make today count.",
    },
    "314": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "The forecast is vague; your day's still great!",
    },
    "317": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "Skies are undecided, but your day's a canvas.",
    },
    "320": {
        "description": "LightSnow",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#DDE7F0",
        "quote": "Soft snow falling, hushes the ground. A peaceful silence all around.",
    },
    "323": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
        "color": "#B9D1E8",
        "quote": "Let the chill of snow invigorate your day. A fresh, crisp start in a magical way",
    },
    "326": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
        "color": "#B9D1E8",
        "quote": "Snow-covered trees, a breathtaking sight. Step into the beauty of pure, white light.",
    },
    "329": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#E3EDF6",
        "quote": "A blanket of snow, fresh and serene. Step outside, feel the crisp, winter scene.",
    },
    "332": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#E3EDF6",
        "quote": "The silent descent of snow. A perfect hush, a gentle glow.",
    },
    "335": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "snow",
        "image-night": "snow",
        "color": "#D4E2F0",
        "quote": "Snow is here, hushed and bright. A cozy day awaits, bathed in soft light.",
    },
    "338": {
        "description": "HeavySnow",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnow"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnow"],
        "image": "snow",
        "image-night": "snow",
        "color": "#E3EDF6",
        "quote": "Winter's white magic fills the air. A crisp, pure beauty beyond compare.",
    },
    "350": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "The forecast is vague; your day's still great!",
    },
    "353": {
        "description": "LightShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#6BA4E2",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "356": {
        "description": "HeavyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyShowers"],
        "image": "rain",
        "image-night": "rain",
        "color": "#4A6A8C",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "359": {
        "description": "HeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavyRain"],
        "image": "rain",
        "image-night": "rain",
        "color": "#405772",
        "quote": "It's rainy, it's a great day! \nGet some ramen and watch as the rain falls",
    },
    "362": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#91A8B6",
        "quote": "The forecast is vague; your day's still great!",
    },
    "365": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#91A8B6",
        "quote": "Mystery in the clouds, embrace what unfolds.",
    },
    "368": {
        "description": "LightSnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSnowShowers"],
        "image": "snow",
        "image-night": "snow",
        "color": "#B9D1E8",
        "quote": "It's snowing, it's a great day! \nGet some ramen and watch as the snow falls",
    },
    "371": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "snow",
        "image-night": "snow",
        "color": "#D4E2F0",
        "quote": "Bundle up warm, the snow calls your name. A winter's tale, a beautiful game",
    },
    "374": {
        "description": "LightSleetShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleetShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleetShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#91A8B6",
        "quote": "The forecast is vague; your day's still great!",
    },
    "377": {
        "description": "LightSleet",
        "icon": WEATHER_SYMBOL_WI_DAY["LightSleet"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["LightSleet"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A3B8C9",
        "quote": "Uncertain skies? Find joy anyway.",
    },
    "386": {
        "description": "ThunderyShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#5B6D7A",
        "quote": "There's thunder in the air, showers will soon appear \nFind a cozy spot indoors, and let the storm draw near",
    },
    "389": {
        "description": "ThunderyHeavyRain",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderyHeavyRain"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderyHeavyRain"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#3B4C61",
        "quote": "There's thunder in the air, showers will soon appear \nFind a cozy spot indoors, and let the storm draw near",
    },
    "392": {
        "description": "ThunderySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["ThunderySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["ThunderySnowShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#A1B5CC",
        "quote": "Sort of odd, I don't know what to forecast \nMake sure you have a good time!",
    },
    "395": {
        "description": "HeavySnowShowers",
        "icon": WEATHER_SYMBOL_WI_DAY["HeavySnowShowers"],
        "icon-night": WEATHER_SYMBOL_WI_NIGHT["HeavySnowShowers"],
        "image": "sleet",
        "image-night": "sleet",
        "color": "#D4E2F0",
        "quote": "Sort of odd, I don't know what to forecast \nMake sure you have a good time!",
    },
}
